[[constraint]]
  name = "k8s.io/kubernetes"
  version = "~1.12.1"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/client-go"
  branch = "release-8.0"

[[constraint]]
  name = "github.com/sylabs/singularity"
  source = "github.com/sashayakovtseva/singularity"
  revision = "86676d1896f2ec34141c7d3a782782b7b915ccee"

[[constraint]]
  name = "github.com/sylabs/sif"
  version = "v1.0.1"

[[constraint]]
  name = "github.com/kr/pty"
  version = "v1.1.3"

[[constraint]]
  name = "github.com/opencontainers/selinux"
  version = "v1.0.0-rc1"

[[constraint]]
  name = "github.com/opencontainers/runc"
  version = "v1.0.0-rc6"

# patched fork from github.com/golang/crypto
[[override]]
  branch = "master"
  name = "golang.org/x/crypto"
  source = "github.com/sylabs/golang-x-crypto"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
