version: 2.0

defaults: &defaults
  working_directory: /go/src/github.com/sylabs/cri
  docker:
    - image: sylabsio/golang:1.11-stretch

jobs:
  get_source:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Install dep tool
          command: |-
            curl -s https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Set up vendor directory
          command: |-
            if [ ! -d vendor ]; then
              dep ensure -vendor-only
            fi
      - save_cache:
          key: dep-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: /
          paths:
            - go/src/github.com/sylabs/cri/*

  gometalinter_check:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /
    - run:
        name: Install gometalinter
        command: |-
          cd /
          curl -L https://git.io/vp6lP | sh
    - run:
        name: Check formatting
        working_directory: /go/src/github.com/sylabs/cri
        command: |-
          make lint

  build_source:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Singularity 3.0 dependencies
          command: |-
            apt-get update && apt-get install -y build-essential libssl-dev uuid-dev squashfs-tools
            curl -s https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Build source
          working_directory: /go/src/github.com/sylabs/cri
          command:
            make build

  unit_test:
    <<: *defaults
    machine: true
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Singularity 3.0 dependencies
          command: |-
            apt-get update && apt-get install -y build-essential libssl-dev uuid-dev squashfs-tools
            curl -s https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Singularity 3.0
          command: |-
            git clone https://github.com/sylabs/singularity.git /go/src/github.com/sylabs/singularity
            cd /go/src/github.com/sylabs/singularity
            ./mconfig
            make -j$(nproc) -C ./builddir
            sudo make -C ./builddir install
      - run:
          name: Run tests
          working_directory: /go/src/github.com/sylabs/cri
          command:
            make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - get_source
      - gometalinter_check:
          requires:
            - get_source
      - unit_test:
          requires:
            - get_source
      - build_source:
          requires:
            - get_source
